/// Who authored a given message in a conversation thread.
enum MessageSender {
  /// The end customer, messaging in from the support channel.
  customer,

  /// An automated reply generated by the AI.
  ai,

  /// A human support agent, replying manually after taking over.
  agent,

  /// Not an actual chat message - a system note inserted into the thread
  /// (e.g. "the AI flagged this conversation for human attention").
  system,
}
